ALTER TABLE invoices ADD COLUMN seller_gstin VARCHAR(32) DEFAULT '00PLACEHOLDER' NOT NULL;
ALTER TABLE invoices ADD COLUMN place_of_supply VARCHAR(2) DEFAULT '00' NOT NULL;
ALTER TABLE invoices ADD COLUMN line_items_json CLOB DEFAULT '[]' NOT NULL;

